#!/usr/bin/env bash
# Stage the platform's shared code and image recipe into this agent's Docker build context.
#
# `agentcore configure/launch` builds from this directory, so the image cannot reach
# ../../geo_agent. This script copies exactly the allowlist below and generates the Dockerfile
# from the platform's, so the Methane Hunter runs the same pinned geo stack (Miniforge,
# GDAL/rasterio pins, the sqlite fix) as the Earth Analyst and cannot drift from it.
#
#   ./stage_shared.sh            # copy code + requirements, generate Dockerfile
#   ./stage_shared.sh dockerfile # regenerate only the Dockerfile (after `agentcore configure`,
#                                # which overwrites it)
#
# Everything this writes is gitignored. tests/test_staging.py parses the two arrays below and
# fails if an agent module imports shared code that is not staged.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$(cd "$HERE/../../geo_agent" && pwd)"
DEST="$HERE/_geo_agent"

# --- allowlist (keep one item per line; parsed by tests/test_staging.py) --------------------
SHARED_FILES=(
    config.py
)
SHARED_DIRS=(
    utils
    data
)
# --------------------------------------------------------------------------------------------

generate_dockerfile() {
    local platform="$SRC/Dockerfile_geospatial_agent_on_aws"
    # Only the entrypoint module differs; fail loudly if the platform CMD ever changes shape.
    if ! grep -q 'python -m geospatial_agent_on_aws' "$platform"; then
        echo "stage_shared.sh: platform Dockerfile CMD changed; update generate_dockerfile()" >&2
        exit 1
    fi
    {
        echo "# GENERATED by stage_shared.sh from geo_agent/Dockerfile_geospatial_agent_on_aws."
        echo "# Do not edit; change the platform Dockerfile instead."
        sed 's/python -m geospatial_agent_on_aws/python -m methane_hunter/g' "$platform"
    } > "$HERE/Dockerfile"
}

if [ "${1:-}" = "dockerfile" ]; then
    generate_dockerfile
    echo "Dockerfile regenerated from the platform Dockerfile."
    exit 0
fi

rm -rf "$DEST"
mkdir -p "$DEST"
for f in "${SHARED_FILES[@]}"; do
    cp "$SRC/$f" "$DEST/$f"
done
for d in "${SHARED_DIRS[@]}"; do
    rsync -a --delete --exclude '__pycache__' --exclude '*.pyc' --exclude '.env*' "$SRC/$d/" "$DEST/$d/"
done
cp "$SRC/requirements.txt" "$HERE/requirements.txt"
generate_dockerfile

echo "Staged shared code into $DEST (${SHARED_FILES[*]} ${SHARED_DIRS[*]}), requirements.txt and Dockerfile."
